from flask import Flask, request, jsonify, send_from_directory, send_file
from flask_cors import CORS
from flask_socketio import SocketIO, emit
import os
import threading
from datetime import datetime
from io import BytesIO
import json
import time
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE

import database as db
from recorder import get_recorder, list_audio_devices, get_default_input_device
from transcriber import (
    cleanup_audio_file, get_available_models,
    preload_model, transcribe_audio_chunk, get_ollama_status,
    get_correction_status, reset_session, get_text_corrector
)

app = Flask(__name__, static_folder='static')
CORS(app)
socketio = SocketIO(app, cors_allowed_origins="*", async_mode='threading')

realtime_active = False
realtime_thread = None
correction_thread = None
current_transcription = []
corrected_segments = []
last_correction_index = 0
correction_lock = threading.Lock()
current_language = "de"

CORRECTION_DELAY_SECONDS = 10

threading.Thread(target=preload_model, daemon=True).start()


def create_word_document(note):
    doc = Document()

    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(11)

    title = doc.add_heading(note['title'], level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.color.rgb = RGBColor(41, 98, 255)

    meta_para = doc.add_paragraph()
    meta_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    date_run = meta_para.add_run(f"Created: {note['created_at']}")
    date_run.font.size = Pt(10)
    date_run.font.color.rgb = RGBColor(128, 128, 128)
    date_run.font.italic = True

    if note.get('language'):
        lang_display = "German" if note['language'] == 'de' else "English"
        meta_para.add_run("  •  ")
        lang_run = meta_para.add_run(f"Language: {lang_display}")
        lang_run.font.size = Pt(10)
        lang_run.font.color.rgb = RGBColor(128, 128, 128)
        lang_run.font.italic = True

    if note.get('audio_duration') and note['audio_duration'] > 0:
        mins = int(note['audio_duration'] // 60)
        secs = int(note['audio_duration'] % 60)
        meta_para.add_run("  •  ")
        dur_run = meta_para.add_run(f"Duration: {mins:02d}:{secs:02d}")
        dur_run.font.size = Pt(10)
        dur_run.font.color.rgb = RGBColor(128, 128, 128)
        dur_run.font.italic = True

    if note.get('tags') and len(note['tags']) > 0:
        doc.add_paragraph()
        tags_para = doc.add_paragraph()
        tags_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        tags_label = tags_para.add_run("Tags: ")
        tags_label.font.bold = True
        tags_label.font.size = Pt(10)
        tags_label.font.color.rgb = RGBColor(100, 100, 100)

        for i, tag in enumerate(note['tags']):
            tag_run = tags_para.add_run(f" {tag} ")
            tag_run.font.size = Pt(9)
            tag_run.font.color.rgb = RGBColor(255, 255, 255)
            tag_run.font.bold = True
            if i < len(note['tags']) - 1:
                tags_para.add_run("  ")

    doc.add_paragraph()
    doc.add_paragraph("─" * 50)
    doc.add_paragraph()

    content_heading = doc.add_heading("Transcription", level=1)
    for run in content_heading.runs:
        run.font.color.rgb = RGBColor(60, 60, 60)

    paragraphs = note['content'].split('\n\n') if note.get('content') else ['']
    for para_text in paragraphs:
        if para_text.strip():
            content_para = doc.add_paragraph()
            content_para.paragraph_format.space_after = Pt(12)
            content_para.paragraph_format.line_spacing = 1.5

            content_run = content_para.add_run(para_text.strip())
            content_run.font.size = Pt(11)
            content_run.font.color.rgb = RGBColor(40, 40, 40)

    doc.add_paragraph()
    doc.add_paragraph()

    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer.add_run("─" * 30)
    footer_run.font.color.rgb = RGBColor(200, 200, 200)

    footer2 = doc.add_paragraph()
    footer2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer2_run = footer2.add_run("Generated by VoiceNotes")
    footer2_run.font.size = Pt(9)
    footer2_run.font.color.rgb = RGBColor(150, 150, 150)
    footer2_run.font.italic = True

    return doc


def create_folder_word_document(folder, notes):
    doc = Document()

    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(11)

    title = doc.add_heading(folder['name'], level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.color.rgb = RGBColor(41, 98, 255)

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = subtitle.add_run(f"{len(notes)} Voice Notes")
    sub_run.font.size = Pt(12)
    sub_run.font.color.rgb = RGBColor(128, 128, 128)
    sub_run.font.italic = True

    doc.add_paragraph()

    toc_heading = doc.add_heading("Contents", level=1)
    for run in toc_heading.runs:
        run.font.color.rgb = RGBColor(60, 60, 60)

    for i, note in enumerate(notes, 1):
        toc_item = doc.add_paragraph()
        toc_run = toc_item.add_run(f"{i}. {note['title']}")
        toc_run.font.size = Pt(10)
        toc_run.font.color.rgb = RGBColor(80, 80, 80)
        date_run = toc_item.add_run(f"  ({note['created_at']})")
        date_run.font.size = Pt(9)
        date_run.font.color.rgb = RGBColor(150, 150, 150)

    doc.add_page_break()

    for i, note in enumerate(notes):
        note_title = doc.add_heading(note['title'], level=1)
        for run in note_title.runs:
            run.font.color.rgb = RGBColor(41, 98, 255)

        meta_para = doc.add_paragraph()
        date_run = meta_para.add_run(f"Created: {note['created_at']}")
        date_run.font.size = Pt(10)
        date_run.font.color.rgb = RGBColor(128, 128, 128)
        date_run.font.italic = True

        if note.get('audio_duration') and note['audio_duration'] > 0:
            mins = int(note['audio_duration'] // 60)
            secs = int(note['audio_duration'] % 60)
            meta_para.add_run("  •  ")
            dur_run = meta_para.add_run(f"Duration: {mins:02d}:{secs:02d}")
            dur_run.font.size = Pt(10)
            dur_run.font.color.rgb = RGBColor(128, 128, 128)
            dur_run.font.italic = True

        if note.get('tags') and len(note['tags']) > 0:
            tags_para = doc.add_paragraph()
            tags_label = tags_para.add_run("Tags: ")
            tags_label.font.bold = True
            tags_label.font.size = Pt(10)
            for tag in note['tags']:
                tag_run = tags_para.add_run(f" {tag} ")
                tag_run.font.size = Pt(9)
                tag_run.font.color.rgb = RGBColor(41, 98, 255)

        doc.add_paragraph()

        paragraphs = note['content'].split('\n\n') if note.get('content') else ['']
        for para_text in paragraphs:
            if para_text.strip():
                content_para = doc.add_paragraph()
                content_para.paragraph_format.space_after = Pt(12)
                content_para.paragraph_format.line_spacing = 1.5
                content_run = content_para.add_run(para_text.strip())
                content_run.font.size = Pt(11)
                content_run.font.color.rgb = RGBColor(40, 40, 40)

        if i < len(notes) - 1:
            doc.add_paragraph()
            divider = doc.add_paragraph()
            divider.alignment = WD_ALIGN_PARAGRAPH.CENTER
            div_run = divider.add_run("─" * 40)
            div_run.font.color.rgb = RGBColor(200, 200, 200)
            doc.add_paragraph()

    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer.add_run("Generated by VoiceNotes")
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(150, 150, 150)
    footer_run.font.italic = True

    return doc


@app.route('/')
def index():
    return send_from_directory('static', 'index.html')

@app.route('/static/<path:path>')
def serve_static(path):
    return send_from_directory('static', path)


def background_correction_worker():
    global realtime_active, current_transcription, corrected_segments, last_correction_index, current_language

    corrector = get_text_corrector(current_language)

    while realtime_active:
        time.sleep(2)

        if not realtime_active:
            break

        with correction_lock:
            total_segments = len(current_transcription)
            safe_index = max(0, total_segments - 3)

            if safe_index > last_correction_index:
                segments_to_correct = current_transcription[last_correction_index:safe_index]

                if segments_to_correct:
                    text_to_correct = ' '.join(segments_to_correct)
                    corrected_text = corrector.correct_full(text_to_correct)

                    corrected_segments.append(corrected_text)
                    last_correction_index = safe_index

                    full_corrected = ' '.join(corrected_segments)
                    remaining = ' '.join(current_transcription[safe_index:])
                    if remaining:
                        full_corrected += ' ' + remaining

                    socketio.emit('correction_update', {
                        'corrected_text': full_corrected,
                        'segments_corrected': safe_index,
                        'total_segments': total_segments
                    })


def realtime_transcription_worker():
    global realtime_active, current_transcription, current_language

    recorder = get_recorder()
    corrector = get_text_corrector(current_language)

    while realtime_active and recorder.is_recording():
        chunk = recorder.get_next_chunk(timeout=0.5)

        if chunk is not None:
            try:
                raw_text, corrected_text, confidence = transcribe_audio_chunk(
                    chunk,
                    sample_rate=recorder.sample_rate,
                    language=current_language,
                    apply_instant_correction=True
                )

                if corrected_text and corrected_text.strip():
                    with correction_lock:
                        current_transcription.append(corrected_text.strip())
                        full_text = ' '.join(current_transcription)

                    full_corrected = corrector.correct_instant(full_text)

                    socketio.emit('transcription_update', {
                        'text': corrected_text.strip(),
                        'raw_text': raw_text.strip() if raw_text else '',
                        'full_text': full_corrected,
                        'confidence': confidence,
                        'is_final': False,
                        'is_corrected': True
                    })

            except Exception as e:
                print(f"Transcription error: {e}")
                import traceback
                traceback.print_exc()


@socketio.on('start_realtime')
def handle_start_realtime(data):
    global realtime_active, realtime_thread, correction_thread
    global current_transcription, corrected_segments, last_correction_index, current_language

    folder_id = data.get('folder_id')
    current_language = data.get('language', 'de')
    recorder = get_recorder()

    if recorder.is_recording():
        emit('error', {'message': 'Already recording'})
        return

    with correction_lock:
        current_transcription = []
        corrected_segments = []
        last_correction_index = 0

    realtime_active = True
    reset_session()

    subject = None
    if folder_id:
        folder = db.get_folder(folder_id)
        if folder:
            subject = folder.get('name')

    recorder.start_recording()

    realtime_thread = threading.Thread(target=realtime_transcription_worker, daemon=True)
    realtime_thread.start()

    correction_thread = threading.Thread(target=background_correction_worker, daemon=True)
    correction_thread.start()

    emit('recording_started', {
        'message': 'Recording started',
        'language': current_language,
        'subject': subject
    })


@socketio.on('stop_realtime')
def handle_stop_realtime(data):
    global realtime_active, current_transcription, corrected_segments, last_correction_index, current_language

    folder_id = data.get('folder_id')
    recorder = get_recorder()

    if not recorder.is_recording():
        emit('error', {'message': 'Not recording'})
        return

    realtime_active = False
    audio_path, duration = recorder.stop_recording()

    with correction_lock:
        if last_correction_index < len(current_transcription):
            remaining_segments = current_transcription[last_correction_index:]
            if remaining_segments:
                corrector = get_text_corrector(current_language)
                remaining_text = ' '.join(remaining_segments)
                corrected_remaining = corrector.correct_full(remaining_text)
                corrected_segments.append(corrected_remaining)

        final_text = ' '.join(corrected_segments)

    if not final_text.strip():
        final_text = ' '.join(current_transcription)
        if final_text.strip():
            corrector = get_text_corrector(current_language)
            final_text = corrector.correct_full(final_text)

    if audio_path:
        cleanup_audio_file(audio_path)

    if final_text.strip():
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        title = f"Voice Note - {timestamp}"

        note_id = db.create_note(
            title=title,
            content=final_text,
            folder_id=folder_id,
            language=current_language,
            audio_duration=duration
        )

        note = db.get_note(note_id)

        emit('recording_stopped', {
            'success': True,
            'note': note,
            'final_text': final_text,
            'duration': duration
        })
    else:
        emit('recording_stopped', {
            'success': False,
            'message': 'No speech detected'
        })


@socketio.on('set_language')
def handle_set_language(data):
    global current_language
    current_language = data.get('language', 'de')
    emit('language_changed', {'language': current_language})


@app.route('/api/recording/start', methods=['POST'])
def start_recording():
    recorder = get_recorder()
    if recorder.is_recording():
        return jsonify({'success': False, 'error': 'Already recording'}), 400

    reset_session()
    success = recorder.start_recording()
    return jsonify({'success': success})

@app.route('/api/recording/stop', methods=['POST'])
def stop_recording():
    global current_language, current_transcription
    recorder = get_recorder()
    if not recorder.is_recording():
        return jsonify({'success': False, 'error': 'Not recording'}), 400

    data = request.get_json() or {}
    folder_id = data.get('folder_id')
    language = data.get('language', current_language)

    audio_path, duration = recorder.stop_recording()

    if not audio_path:
        return jsonify({'success': False, 'error': 'No audio recorded'}), 400

    corrector = get_text_corrector(language)
    final_text = corrector.correct_full(' '.join(current_transcription))
    cleanup_audio_file(audio_path)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    title = f"Voice Note - {timestamp}"

    note_id = db.create_note(
        title=title,
        content=final_text,
        folder_id=folder_id,
        language=language,
        audio_duration=duration
    )

    note = db.get_note(note_id)

    return jsonify({
        'success': True,
        'note': note,
        'transcription': {
            'text': final_text,
            'language': language,
            'duration': duration
        }
    })

@app.route('/api/recording/status', methods=['GET'])
def recording_status():
    recorder = get_recorder()
    return jsonify({
        'recording': recorder.is_recording(),
        'duration': recorder.get_duration()
    })

@app.route('/api/audio/devices', methods=['GET'])
def audio_devices():
    devices = list_audio_devices()
    default = get_default_input_device()
    return jsonify({'devices': devices, 'default': default})


@app.route('/api/folders', methods=['GET'])
def get_folders():
    parent_id = request.args.get('parent_id', type=int)
    if request.args.get('all') == 'true':
        folders = db.get_all_folders()
    else:
        folders = db.get_folders(parent_id)
    return jsonify({'folders': folders})

@app.route('/api/folders', methods=['POST'])
def create_folder():
    data = request.get_json()
    if not data or not data.get('name'):
        return jsonify({'error': 'Name is required'}), 400

    folder_id = db.create_folder(name=data['name'], parent_id=data.get('parent_id'))
    folder = db.get_folder(folder_id)
    return jsonify({'folder': folder}), 201

@app.route('/api/folders/<int:folder_id>', methods=['GET'])
def get_folder(folder_id):
    folder = db.get_folder(folder_id)
    if not folder:
        return jsonify({'error': 'Folder not found'}), 404
    return jsonify({'folder': folder})

@app.route('/api/folders/<int:folder_id>', methods=['PUT'])
def update_folder(folder_id):
    data = request.get_json()
    if not data or not data.get('name'):
        return jsonify({'error': 'Name is required'}), 400

    success = db.rename_folder(folder_id, data['name'])
    if not success:
        return jsonify({'error': 'Folder not found'}), 404

    folder = db.get_folder(folder_id)
    return jsonify({'folder': folder})

@app.route('/api/folders/<int:folder_id>', methods=['DELETE'])
def delete_folder(folder_id):
    success = db.delete_folder(folder_id)
    if not success:
        return jsonify({'error': 'Folder not found'}), 404
    return jsonify({'success': True})

@app.route('/api/folders/<int:folder_id>/subfolders', methods=['GET'])
def get_subfolders(folder_id):
    subfolders = db.get_folders(folder_id)
    return jsonify({'folders': subfolders})


@app.route('/api/notes', methods=['GET'])
def get_notes():
    folder_id = request.args.get('folder_id', type=int)
    notes = db.get_notes(folder_id)
    return jsonify({'notes': notes})

@app.route('/api/notes/<int:note_id>', methods=['GET'])
def get_note(note_id):
    note = db.get_note(note_id)
    if not note:
        return jsonify({'error': 'Note not found'}), 404
    return jsonify({'note': note})

@app.route('/api/notes/<int:note_id>', methods=['PUT'])
def update_note(note_id):
    data = request.get_json()
    if not data:
        return jsonify({'error': 'No data provided'}), 400

    success = db.update_note(
        note_id,
        title=data.get('title'),
        content=data.get('content'),
        folder_id=data.get('folder_id')
    )

    if not success:
        return jsonify({'error': 'Note not found or no changes'}), 404

    note = db.get_note(note_id)
    return jsonify({'note': note})

@app.route('/api/notes/<int:note_id>', methods=['DELETE'])
def delete_note(note_id):
    success = db.delete_note(note_id)
    if not success:
        return jsonify({'error': 'Note not found'}), 404
    return jsonify({'success': True})

@app.route('/api/notes/search', methods=['GET'])
def search_notes():
    query = request.args.get('q', '')
    if not query:
        return jsonify({'notes': []})
    notes = db.search_notes(query)
    return jsonify({'notes': notes})


@app.route('/api/tags', methods=['GET'])
def get_tags():
    tags = db.get_all_tags()
    return jsonify({'tags': tags})

@app.route('/api/notes/<int:note_id>/tags', methods=['POST'])
def add_tag(note_id):
    data = request.get_json()
    if not data or not data.get('tag'):
        return jsonify({'error': 'Tag is required'}), 400

    success = db.add_tag_to_note(note_id, data['tag'])
    note = db.get_note(note_id)
    return jsonify({'note': note, 'added': success})

@app.route('/api/notes/<int:note_id>/tags/<tag_name>', methods=['DELETE'])
def remove_tag(note_id, tag_name):
    success = db.remove_tag_from_note(note_id, tag_name)
    note = db.get_note(note_id)
    return jsonify({'note': note, 'removed': success})

@app.route('/api/tags/<tag_name>/notes', methods=['GET'])
def get_notes_by_tag(tag_name):
    notes = db.get_notes_by_tag(tag_name)
    return jsonify({'notes': notes})


@app.route('/api/notes/<int:note_id>/export', methods=['GET'])
def export_note(note_id):
    format_type = request.args.get('format', 'txt')
    note = db.get_note(note_id)

    if not note:
        return jsonify({'error': 'Note not found'}), 404

    if format_type == 'docx':
        doc = create_word_document(note)
        buffer = BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        safe_title = "".join(c for c in note['title'] if c.isalnum() or c in ' -_').strip()
        filename = f"{safe_title}.docx"
        return send_file(buffer, as_attachment=True, download_name=filename,
                        mimetype='application/vnd.openxmlformats-officedocument.wordprocessingml.document')

    elif format_type == 'md':
        content = f"# {note['title']}\n\n"
        content += f"*Created: {note['created_at']}*\n\n"
        if note['tags']:
            content += f"**Tags:** {', '.join(note['tags'])}\n\n"
        content += "---\n\n"
        content += note['content']
        filename = f"{note['title']}.md"
        mimetype = 'text/markdown'
    else:
        content = f"{note['title']}\n"
        content += f"Created: {note['created_at']}\n"
        if note['tags']:
            content += f"Tags: {', '.join(note['tags'])}\n"
        content += "\n" + "=" * 40 + "\n\n"
        content += note['content']
        filename = f"{note['title']}.txt"
        mimetype = 'text/plain'

    buffer = BytesIO()
    buffer.write(content.encode('utf-8'))
    buffer.seek(0)

    return send_file(buffer, as_attachment=True, download_name=filename, mimetype=mimetype)

@app.route('/api/folders/<int:folder_id>/export', methods=['GET'])
def export_folder(folder_id):
    format_type = request.args.get('format', 'md')
    folder = db.get_folder(folder_id)
    notes = db.get_notes(folder_id)

    if not folder:
        return jsonify({'error': 'Folder not found'}), 404

    if format_type == 'docx':
        doc = create_folder_word_document(folder, notes)
        buffer = BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        safe_name = "".join(c for c in folder['name'] if c.isalnum() or c in ' -_').strip()
        filename = f"{safe_name}.docx"
        return send_file(buffer, as_attachment=True, download_name=filename,
                        mimetype='application/vnd.openxmlformats-officedocument.wordprocessingml.document')

    elif format_type == 'md':
        content = f"# {folder['name']}\n\n"
        for note in notes:
            content += f"## {note['title']}\n\n"
            content += f"*Created: {note['created_at']}*\n\n"
            content += note['content'] + "\n\n---\n\n"
        filename = f"{folder['name']}.md"
        mimetype = 'text/markdown'
    else:
        content = f"{folder['name']}\n{'=' * 40}\n\n"
        for note in notes:
            content += f"{note['title']}\n"
            content += f"Created: {note['created_at']}\n"
            content += "-" * 20 + "\n"
            content += note['content'] + "\n\n"
        filename = f"{folder['name']}.txt"
        mimetype = 'text/plain'

    buffer = BytesIO()
    buffer.write(content.encode('utf-8'))
    buffer.seek(0)

    return send_file(buffer, as_attachment=True, download_name=filename, mimetype=mimetype)


@app.route('/api/export/database', methods=['GET'])
def export_database():
    folders = db.get_all_folders()
    notes = db.get_notes()
    tags = db.get_all_tags()

    export_data = {
        'version': '2.0',
        'exported_at': datetime.now().isoformat(),
        'folders': folders,
        'notes': notes,
        'tags': tags
    }

    buffer = BytesIO()
    buffer.write(json.dumps(export_data, indent=2, ensure_ascii=False).encode('utf-8'))
    buffer.seek(0)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"voicenotes_backup_{timestamp}.json"

    return send_file(buffer, as_attachment=True, download_name=filename, mimetype='application/json')


@app.route('/api/settings/models', methods=['GET'])
def get_models():
    models = get_available_models()
    return jsonify({'models': models})

@app.route('/api/settings/ollama', methods=['GET'])
def get_ollama():
    status = get_ollama_status()
    return jsonify(status)

@app.route('/api/settings/status', methods=['GET'])
def get_system_status():
    correction = get_correction_status()

    return jsonify({
        'offline_ready': True,
        'ai_correction': correction['ai_correction'],
        'speaker_diarization': correction['speaker_diarization'],
        'whisper': {
            'realtime_model': 'small',
            'processing': 'live'
        }
    })

if __name__ == '__main__':
    print("\n" + "=" * 50)
    print("  Voice Notes - Real-time Transcription")
    print("  Open http://localhost:5050 in your browser")
    print("=" * 50 + "\n")
    socketio.run(app, host='127.0.0.1', port=5050, debug=False, allow_unsafe_werkzeug=True)
