#!/bin/bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

BUILD_FILE="$PROJECT_DIR/build_number.txt"
BUILD_VERSION_FILE="$PROJECT_DIR/build_version.txt"
BUILD_INFO="$PROJECT_DIR/lib/build_info.dart"

read_version() {
  VERSION=$(grep "static const String version = " "$BUILD_INFO" 2>/dev/null | sed "s/.*= '//;s/'.*//" || echo "0.4")
  VERSION_NAME=$(grep "static const String versionName = " "$BUILD_INFO" 2>/dev/null | sed "s/.*= '//;s/'.*//" || echo "0.4 Closed Beta")
}

increment_build_number() {
  # Build number is a single, monotonically increasing counter. It must NEVER
  # reset on a version-name change, because it feeds Android versionCode and
  # macOS CFBundleVersion, which the OS requires to only ever increase —
  # otherwise updates fail with INSTALL_FAILED_VERSION_DOWNGRADE.
  BUILD_NUM=$(cat "$BUILD_FILE" 2>/dev/null || echo "0")
  BUILD_NUM=$((BUILD_NUM + 1))

  echo "$BUILD_NUM" > "$BUILD_FILE"
  echo "$VERSION" > "$BUILD_VERSION_FILE"
}

update_pubspec_version() {
  # Keep pubspec's +buildNumber in sync with the scripted counter so an
  # unscripted build (e.g. `flutter build ios`, which has no wrapper script)
  # does not ship a stale, lower versionCode than the last scripted release.
  local pubspec="$PROJECT_DIR/pubspec.yaml"
  [ -f "$pubspec" ] || return 0
  python3 -c "
import re
p='$pubspec'
s=open(p).read()
s=re.sub(r'^(version:\s*[0-9]+\.[0-9]+\.[0-9]+)\+[0-9]+', r'\g<1>+$BUILD_NUM', s, count=1, flags=re.M)
open(p,'w').write(s)
"
  echo "Synced pubspec build number → +$BUILD_NUM"
}

generate_build_info() {
  local script_name="${1:-build script}"
  cat > "$BUILD_INFO" << DART
// AUTO-GENERATED — do not edit manually
// Generated by scripts/$script_name
class BuildInfo {
  static const String version = '$VERSION';
  static const String versionName = '$VERSION_NAME';
  static const int buildNumber = $BUILD_NUM;
  static const String fullVersion = '$VERSION Build $BUILD_NUM';
}
DART
}

update_version_json() {
  local version_json="$PROJECT_DIR/../landing-page/public/version.json"
  if [ -f "$version_json" ]; then
    local today
    today=$(date +%Y-%m-%d)
    python3 -c "
import json, sys
with open('$version_json', 'r') as f:
    data = json.load(f)
data['version'] = '$VERSION'
data['versionName'] = '$VERSION_NAME'
data['releaseDate'] = '$today'
with open('$version_json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write('\n')
"
    echo "Updated version.json → $VERSION_NAME ($today)"
  fi
}

prepare_build() {
  local script_name="$1"
  read_version
  increment_build_number
  generate_build_info "$script_name"
  update_pubspec_version
  update_version_json
  echo "=== Nexus Build $BUILD_NUM ($VERSION_NAME) ==="
}
