// AUTO-GENERATED — do not edit manually
// Generated by scripts/build_macos.sh
class BuildInfo {
  static const String version = '0.3';
  static const String versionName = '0.3 Closed Beta';
  static const int buildNumber = 33;
  static const String fullVersion = '0.3 Build 33';
}
